### ISSUE TITLE
Default value for PV_SYSTEM_TEST_THREADS

### ISSUE THREAD

**Issue by slundqui** [PetaVision/OpenPV#32] opened 2016-02-02 20:57 UTC
Can we make the default value of PV_SYSTEM_TEST_THREADS to something other than "use all threads"? As the system tests run with MPI as well, with this default value, I constantly overload my machine with way too many cores (num MPI \* max number of threads), such that it takes forever to run. I suggest using 2.

**Comment by peteschultz** [comment] 2016-02-02 21:18
HyPerCol::initialize should be dividing by the number of MPI processes if you use the default number of threads (HyPerCol.cpp line 382).  So the total number of cores being used should be no more than max number of threads.  I'd propose tracking down whatever bug is causing this not to happen, instead of changing the default to a fixed number.

It may also be that omp_max_num_threads() is too high for the total number of cores; perhaps the default should be a little less than omp_max_num_threads.

**Comment by slundqui** [comment] 2016-02-02 21:21
I didn't realize the threads were getting divided by the MPI processes. But either way, it seems that whenever I run system tests, my machine pretty much freezes (not using the -j flag in ctest). I've crashed neuro and agave multiple times doing the same thing as well.

**Comment by slundqui** [comment] 2016-02-02 21:25
Sorry I should add that I'm using 2 openmp threads when it crashes. Additionally, my machine (which is in the middle of crashing) spat out something about running low on memory on the system test InitWeightsTest.

**Comment by peteschultz** [comment] 2016-02-16 18:41
We haven't observed any problems along these lines with neuro or agave, beyond the known NFS slowness issues.  In any case, the behavior of PV_SYSTEM_TEST_THREADS does not seem to be the cause, so I've closed this issue.

**Closed as completed by peteschultz** 2016-02-16 18:41 UTC
